"use strict";
// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **
Object.defineProperty(exports, "__esModule", { value: true });
exports.TableServiceClient = exports.RowAccessPolicyServiceClient = exports.RoutineServiceClient = exports.ProjectServiceClient = exports.ModelServiceClient = exports.JobServiceClient = exports.DatasetServiceClient = void 0;
var dataset_service_client_1 = require("./dataset_service_client");
Object.defineProperty(exports, "DatasetServiceClient", { enumerable: true, get: function () { return dataset_service_client_1.DatasetServiceClient; } });
var job_service_client_1 = require("./job_service_client");
Object.defineProperty(exports, "JobServiceClient", { enumerable: true, get: function () { return job_service_client_1.JobServiceClient; } });
var model_service_client_1 = require("./model_service_client");
Object.defineProperty(exports, "ModelServiceClient", { enumerable: true, get: function () { return model_service_client_1.ModelServiceClient; } });
var project_service_client_1 = require("./project_service_client");
Object.defineProperty(exports, "ProjectServiceClient", { enumerable: true, get: function () { return project_service_client_1.ProjectServiceClient; } });
var routine_service_client_1 = require("./routine_service_client");
Object.defineProperty(exports, "RoutineServiceClient", { enumerable: true, get: function () { return routine_service_client_1.RoutineServiceClient; } });
var row_access_policy_service_client_1 = require("./row_access_policy_service_client");
Object.defineProperty(exports, "RowAccessPolicyServiceClient", { enumerable: true, get: function () { return row_access_policy_service_client_1.RowAccessPolicyServiceClient; } });
var table_service_client_1 = require("./table_service_client");
Object.defineProperty(exports, "TableServiceClient", { enumerable: true, get: function () { return table_service_client_1.TableServiceClient; } });
